# Generated by Django 3.2.9 on 2021-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todouhuken',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
